[package]
name = "space"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.16.3"
num = "0.2.0"
derive_more = "0.12.0"
itertools = "0.7.8"