[package]
name = "space"
version = "0.1.1"
description = "A library for working with spatial trees and point clouds"
documentation = "https://docs.rs/space/"
repository = "https://github.com/vadixidav/space"
keywords = ["space", "pointcloud", "octree", "morton", "spatial"]
license = "MIT"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

edition = "2018"

[dependencies]
nalgebra = "0.16.3"
num = "0.2.0"
derive_more = "0.12.0"
itertools = "0.7.8"
either = "1.5.0"
bitwise = "0.1.1"
smallvec = "0.6.5"

[dev-dependencies]
rand = "0.5.5"
criterion = "0.2"

[[bench]]
name = "octree"
harness = false